site_name: Hướng dẫn sử dụng GOCheap!
site_url: https://gocheap.vn
site_description: Cẩm nang hướng dẫn sử dụng GOCheap dành cho đối tác tài xế và khách hàng
theme:
  name: material
  custom_dir: overrides  # Chỉ định thư mục overrides
extra_css:
  - assets/css/custom.css
extra:
  generator: false
  palette:
    primary: purple
    accent: orange
  language: vi
  logo: images/gocheap-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
nav:
  - Trang chủ: index.md
  - Giới thiệu: gioi-thieu.md
  - Đối tác:
      - Thủ tục hợp tác: tai-xe/thu-tuc-hop-tac.md
      - Hợp đồng & Quy định: tai-xe/hop-dong.md
      - Hướng dẫn sử dụng: tai-xe/huong-dan-su-dung-app.md
      - Dịch vụ & Chính sách: tai-xe/dich-vu.md
      - Văn hóa công ty: tai-xe/van-hoa-gocheap.md
      - Câu hỏi thường gặp: tai-xe/cau-hoi-thuong-gap.md
  - Khách hàng:
      - Cài đặt: khach-hang/cai-dat-app.md
      - Thuê lái xe: khach-hang/thue-tai-xe.md
      - Thanh toán: khach-hang/thanh-toan.md
      - Dịch vụ: khach-hang/dich-vu.md
      - Câu hỏi: khach-hang/cau-hoi-thuong-gap.md
  - Hỗ trợ:
      - Liên hệ: ho-tro/lien-he.md
      - Bảo mật: ho-tro/bao-mat.md
      - Điều khoản: ho-tro/dieu-khoan.md    

